# Generated by Django 5.1.2 on 2024-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
