# Generated by Django 5.1.2 on 2024-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_play_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='duration',
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='performances/'),
        ),
    ]
