# Generated by Django 5.1.2 on 2024-10-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plays/"),
        ),
    ]
