# Generated by Django 5.1.1 on 2024-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_alter_play_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("performance", "row", "seat"),
                name="unique_performance_row_seat",
            ),
        ),
    ]
